##############################################################################
# Genome and project-specific files that will change from project-to-project
##############################################################################
antibody_lib:
  /home/groups/CEDAR/roskamsh/projects/Debika_antibody/collapse_antibody_library/antibody_library_sequences.txt
